services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'leonard'
      POSTGRES_PASSWORD: 'Abc@123'
      POSTGRES_DB: 'ecm-postgres'
    volumes:
      - ecm-postgres-volume:/var/lib/postgres/data

  redis:
    image: 'redis:latest'
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    environment:
      REDISCLI_AUTH: 'Q1w2e3r4'
    volumes:
      - redis-data:/var/lib/redis/data
    command: ['redis-server', '--requirepass', 'Q1w2e3r4']

volumes:
  ecm-postgres-volume:
  redis-data:
